language: objective-c

os:
  - osx

install:
  - brew update
  - brew upgrade
  - mkdir -p $(brew --repo)/Library/Taps/meowtimer
  - ln -s $PWD $(brew --repo)/Library/Taps/meowtimer/homebrew-openclonk
  - brew tap --repair

script:
  - brew install openclonk --HEAD -v